#include<stdio.h>
#include<math.h>
#include<conio.h>
#include<stdlib.h>
#include<process.h>
#include<time.h>
#include<ctype.h>
#include<windows.h>

#define UP 72
#define DOWN 80
#define LEFT 75
#define RIGHT 77


void Up();
void Down();
void Left();
void Right();
void Move();//for moving the snake
void Border();//to establidh a boundary for the snake to crawl
int Score();//to keep track of the score points
void Delay(long double);
void Food();//to generate food coordinates
int Scoreonly();//returns score;
void Bend();//handles the bending coordinates
void record();//record the score along with the player name
void Print();//Introduction part
void Exitgame();//check the life count and end the game
void Load();//loading bar

//Move the cursor to desired coordinates
void gotoxy(int x,int y);
void GotoXY(int x,int y);

int len;
char key;
int length;//length of the snake 
int bend_no;//bend_no is incremented each time the snake made a turn
int life;//lifecount of the snake

typedef struct coordinates{
int x;
int y;
int direction;
}coord;
coord body[30],head,food,bend[500];
//bend[500] stores the head at each new position
//head keeps the inital head positions of the snake's body
//food is to store the coordinates of the food generated by Food() function
//body[30] stores the  snakes body coordinates along with its movements 
int main(){
        char key;
        Print();
        system("cls");
        Load();
        length=5;//intial length of the snake along with the head(>) and body(*)
        //intial head position & direction of the snake
        head.x=25;
        head.y=20;
        head.direction=RIGHT;
        
        Border();//block boundary
        Food();//generate food 
        life=3;//intial life count
        bend[0]=head;//initalize bend[0] base address
        Move();//play the game
        return 0;
}

void gotoxy(int x,int y)
{
  COORD coord;
  coord.X=x;
  coord.Y=y;
  SetConsoleCursorPosition(GetCursorHandle(STD_OUTPUT_HANDLE),coord);
}
void GotoXY(int x,int y)
{
  COORD a;
  HANDLE b;
        fflush(stdout);
  b=GetCursorHandle(STD_OUTPUT_HANDLE);
  a.X=x;
  a.Y=y;
  SetConsoleCursorPosition(b,a);
}
void Print(){
  printf("\t\tMini Snake Game\n");
  getch();
  system("cls");
  printf("\tIntroduction to the game\n);
  printf("1-> Use arrow keys to move the snake within the block to fetch the food\n");
  printf("2-> Do not the hit the border\n");
  printf("\t\tEnjoy the game\n");
  if(getch()==27)
         exit(0);
}
void Load(){
  int r,q;
  gotoxy(36,14);
  printf("Loading.....\n");
  gotoxy(34,15);
  for(r=1;r<=10;r++){
  for(q=0;q<=100000000;q++);
  printf("%c",177);
  }
  getch();
}
void Border(){
        system("cls");
        GotoXY(food.x,food.y);
        printf("F");
        int i;
        
        for(i=10;i<71;i++)
        {
                GotoXY(i,10);
                printf("!");
                GotoXY(i,30);
                printf("!");
        }
        for(i=10;i<31;i++)//left and right walls
        {
               GotoXY(10,i);
                printf("!");
               GotoXY(70,i);
                printf("!");
        }
}
void Food(){
if(head.x==food.x && head.y==food.y){
        length++;//snake's length has been increased as new food position is determined
        time_t a;
        a=time(0);
        srand(a);
        food.x=rand()%70;
        if(food.x <=10 )
                food.x+=11;
        food.y=rand()%30;
        if(food.y <=10)
                food.y+=11;
}
else if(food.x==0)//initially all global variables are zero
{
        food.x=rand()%70;
        if(food.x<=10)
                food.x+=11;
        food.y=rand()%30;
        if(food.y<=10)
                food.y+=11;
}
}
int Score(){
        int score;
        score = length-5;
        GotoXY(20,8);
        printf("Score : %d",score);
        GotoXY(50,8);
        printf("Life  : %d",life);
        return score;
}
int Scoreonly(){
        int score=Score();
        system("cls");
        return score;
}
void Delay(long double k){
        Score();
        long double i;
        for(i=0;i<=10000000;i++);
}
void Move(){
int a,i;
        do{
                Food();
                fflush(stdin);
                len=0;
                for(i=0;i<30;i++)
                {
                        body[i].x=body[i].y=30;
                        if(i==length)
                                break;
                }
                Delay(length);
                Border();
                if(head.direction==UP)
                        Up();
                else if(head.direction==DOWN)
                        Down();
                else if(head.direction==RIGHT)
                        Right();
                else if(head.direction==LEFT)
                        Left();
                Exitgame();
        }while(!kbhit());
        a=getch();
        if(a==27)
        {
                system("cls");
                exit(0);
        }
        key=getch();
        if((key==UP&&head.direction!=UP&&head.direction!=DOWN)||(key==DOWN&&head.direction!=UP&&head.direction!=DOWN)||(key==RIGHT&&head.direction!=RIGHT&&head.direction!=LEFT)||(key==LEFT&&head.direction!=LEFT&&head.direction!=RIGHT))
        {
                bend_no++;
                bend[bend_no]=head;
                head.direction=key;
                if(key==UP)
                        head.y--;
                else if(key==DOWN)
                        head.y++:
                else if(key==LEFT)
                        head.x--;
                else if(key==RIGHT)
                        head.x++;
                Move();
        }
        else if(key==27)
        {
                system("cls");
                   exit(0);
        }
        else{
        printf("\a");
                Move();
        }
}
void Bend(){
        int i,j,diff;
        for(i=bend_no;i>=0 && len<length;i--){
                if(bend[i].x==bend[i-1].x){
                diff=bend[i].y-bend[i-1].y;
                        for(j=1;j<=abs(diff);j++){
                        body[len].x=bend[i].x;
                        body[len].y=(diff<0)?bend[i].y+j;bend[i].y-j;
                                GotoXY(body[len].x,body[len].y);
                                printf("*");
                                len++;
                                if(len==length)
                                        break;
                        }
                }
                else if(bend[i].y==bend[i-1].y){
                diff=bend[i].x-bend[i-1].x;
                        for(j=1;j<=abs(diff)&&len<length;j++){
                        body[len].x=(diff<0)?bend[i].x+j;bend[i].x-j;
                        body[len].y=bend[i].y;
                                GotoXY(body[len].x,body[len].y);
                                printf("*");
                                len++;
                                if(len==length)
                                        break;
                        }
                }
        }
}
        void Up(){
        int i;
             for(i=0;i<=(bend[bend_no].y-head.y)&&len<length;i++){
             body[len].x=head.x;
             body[len].y=head.y+i;
                  GotoXY(body[len].x,body[len].y);
                     {
                     if(len==0)
                             printf("^");
                      else 
                              printf("*");
                     }
                     len++;
             }
                
                Bend();
                if(!kbhit())
                        head.y--;
        }
        void Down(){
                int i;
                for(i=0;i<=(head.y-bend[bend_no].y)&&len<length;i++)
                {
                       body[len].x=head.x;
                       body[len].y=head.y-j;
                        GotoXY(body[len].x,body[len].y);
                        {
                        if(len==0)
                                printf("v");
                        else 
                                printf("*");
                        }
                        len++;
                } 
                Bend();
                if(!kbhit())
                    head.y++;
        }
         
        void Right(){
        int i;
                for(i=0;i<=(head.x-bend[bend_no].x)&&len<length;i++){
                        body[len].x=head.x-j;
                        body[len].y=head.y;
                        Goto(body[len].x,body[len].y)
                        {
                                if(len==0)
                                      printf(">");
                                else
                                      printf("*");
                        }
                        len++;
                }
                Bend();
                if(!kbhit())
                   head.x++;
        }
        void Left(){
                int i;
                for(i=0;i<=(bend[bend_no].x-head.x)&&len<length;i++){
                        body[len].x=head.x+j;
                        body[len].y=head.y;
                        Goto(body[len].x,body[len].y);
                        {
                        if(len==0)
                            printf("<");
                         else 
                            printf("*");
                        }
                        len++;
                }
                Bend();
                if(!kbhit())
                        head.x--;
        }
         void Exitgame(){
         int i,check=0;
            //Snake's length should be atleast four to bite itself
                 for(i=4;i<length;i++){
                 if(body[0].x==body[i].x && body[i].y==body[i].y){
                        check++;
                 }
                         if(i=length || check!=0)
                                 break;
                 }
                 if(head.x<=10 ||head.x>=70 || head.y<=10 || head.y>=30)
                 {
                 life--;
                         if(life >= 0){
                               head.x=25;
                               head.y=20;
                               head.direction=RIGHT;
                               Move();
                         }
                         else{
                         system("cls");
                                 printf("\tGame over\nBetter Luck Next time\n");
                                 record();
                                 exit(0);
                         }
                 }
         
         }
         void record(){
         int i,j;
         char plname[20],nplname[20];
         char ch;
         FILE *Info;
         Info = fopen("reocrd.txt","a+");
         getch();
         printf("Enter Your Name : ");
         scanf("%[^\n]s",plname);
         nplname[0]=toupper(planame[0]); 
         for(i=1;planme[i]!='\0';i++)
         {
                if(planme[i-1]==' ')
                {
                        //converting the first character to Uppercase
                        nplname[i]=toupper(plname[i]);
                }
                 else 
                         nplname[i]=planme[i];
         }
         nplname[i]='\0';
         fprintf(Info,"Player Name : %s",nplname);
         fprintf(Info,"Player Score: %s",Scoreonly());
                 for(i=0;i<50;i++)
                         fprintf(Info,"%c",'_');
                        fprintf(Info,"\n");
         fclose(Info);
         printf("Wanna see the past records?(y/n)\n");
         ch=getch();
          if(ch=='y'){
          Info = fopen("record.txt","r");
           do{
           putchar(ch=getc(Info));
           }while(ch!=EOF);
               fclose(Info);
          }
         }
